### ISSUE TITLE
[berkeleyQA branch] Prod build on `92% chunk asset optimization TerserPlugin`

### ISSUE THREAD

**Issue by burnto** [aurowallet/auro-wallet-browser-extension#15]
Attempting to build for berkeleyQA and it's hanging on `92% chunk asset optimization TerserPlugin`. 

This appears to be a [common issue](https://stackoverflow.com/questions/49184787/92-chunk-asset-optimization-webpack), and without digging too far into it I was able to temporarily fix this by disabling `minimize` in the webpack config:

```
    optimization: {
      minimize: false,
    },
```

**Comment by wjdfx** [comment]
This problem may be caused by one mina-signer file being too large before, but this problem is no longer existing with the new version of mina-signer. Thank you for your feedback.
