### ISSUE TITLE
Memo field is not base58 decoded (and unpadded) to display plaintext memo

### ISSUE THREAD

**Issue by Isaac-DeFrain** [aurowallet/auro-wallet-browser-extension#17]
This is the case for extensions

- Firefox (Mozilla Firefox 102.6.0esr)
- Chrome/Chromium (Chromium 90.0.4430.212)

I think this is the relevant [loc ](https://github.com/aurowallet/auro-wallet-browser-extension/blob/27962e547fa1212069b354ff47f81293da8a9f98/src/popup/pages/Record/index.js#L58)

Fixing this will greatly improvement ux wrt on-chain voting which starts Jan 4, 2023

**Comment by wjdfx** [comment]
Thanks for your

**Comment by Isaac-DeFrain** [comment]
Thanks for fixing that so quickly!
