### ISSUE TITLE
Wallet becomes disconnected after being idle

### ISSUE THREAD

**Issue by xendarboh** [aurowallet/auro-wallet-browser-extension#25]
The wallet becomes disconnected after being idle for around 30 seconds. Idle meaning, not performing a wallet function like sign to keep it connected.

Confirmed with both Chrome and Brave browsers on Linux.

I experience this within my zkApp, after the contract compiles (takes a while) or a txn is proven, then the wallet may no longer be connected and attempting to sign something or send a txn will fail with error "please connect first" from here:
https://github.com/aurowallet/auro-wallet-browser-extension/blob/master/src/background/DappService.js#L135

The wallet has to be re-connected (and password re-entered). While the UI still thinks the wallet is connected. Also easily reproduced with the demo @ https://aurowallet.github.io/auro-test-dapp-berkeley/. That's where I determined this idle timeout to be ~30s, then have to reload the demo page, since it does not understand "disconnected", but trying to SIGN results in "Sign result: please connect first".

It's rather painful DX and UX to re-enter wallet password so often. This change happened with recent updates to the extension, within past few weeks. It used to work better.

Perhaps related, I have noticed a console error message from the demo and my zkApp. It doesn't show up immediately, but after some time:
> Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

Additionally, the demo has this error:
> Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.

As a partial workaround, the wallet can be kept connected with a looping function that routinely calls `requestAccounts()`. But this is incomplete with undesired side-effects, as the wallet becomes disconnected between proving a transaction then sending it with the wallet, for example.

**Comment by xendarboh** [comment]
Note: #24 seems related and another symptom is that wallet popup windows can become unresponsive. For example a popup to *confirm* or *cancel* a signing request may become disconnected such that neither button will work, and the window has to be killed.

**Comment by wjdfx** [comment]
It is the root of the same problem as #24
