### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by huyminh1115** [aurowallet/auro-wallet-browser-extension#34]
Currently, I am encountering a issue: 'Timeout'. 
I would greatly appreciate any assistance or recommendations on how to effectively address and rectify this issue.
<img width="271" alt="time-out-error" src="https://github.com/aurowallet/auro-wallet-browser-extension/assets/54903088/6c500044-fe05-44f0-9c02-5bb7fc58fbf2">

I'm using Google Chrome Version 121.0.6167.161, with Auro Wallet version 2.2.13. 
This is my tx data interact with Berkeley chain:
[txData.txt](https://github.com/aurowallet/auro-wallet-browser-extension/files/14258067/txData.txt)

**Comment by lvshaoping007** [comment]
This problem has been fixed. Would you like to try again?
