### ISSUE TITLE
Unable to recreate a second address with Ledger

### ISSUE THREAD

**Issue by canutodev** [aurowallet/auro-wallet-browser-extension#35]
I tried to create a second MINA address through the Ledger Nano s and the Auro wallet. When I created the first address I had no problems, today I tried to create a second address but without success. I carry out the operation, the Ledger displays the new address, I confirm with the ledger and after confirmation the Auro wallet displays the image I have attached
![Screenshot 2024-03-19 alle 22 52 30](https://github.com/aurowallet/auro-wallet-browser-extension/assets/116585931/49b26ad1-aba1-4523-be1b-5f913992a641)

**Comment by wjdfx** [comment]
You certainly can't create multiple addresses with the same Path. 
Change 0 to 1 and keep this number in mind; you'll need it later when you recover your wallet

**Comment by canutodev** [comment]
Why do you close the discussion without even having time to reply? The fact
that you have to change the path is not written anywhere and I think it is
an important thing. I hope that nothing happened to the first stored
address since in the attempt to create the second address, the path
remained the same! I think information like this should be highlighted. The
fact that you have to remember the path for recovery is also something to
highlight, where can I find information on recovery with the Ledger?

Greetings.

Il giorno mer 20 mar 2024 alle ore 02:14 YYQKN ***@***.***>
ha scritto:
