### ISSUE TITLE
Add `o1js` Fields support

### ISSUE THREAD

**Issue by Pfed-prog** [aurowallet/auro-wallet-browser-extension#36]
https://github.com/aurowallet/docs/issues/1

I have noticed that o1js package is not currently in auro wallet https://github.com/aurowallet/auro-wallet-browser-extension/blob/master/package.json

**Comment by lvshaoping007** [comment]
Yes, we plan to add `o1js` in the future to enhance support for zkApp

**Comment by Pfed-prog** [comment]
I am currently using `mina-singer` on the backend to verify the message

```ts
import Client from "mina-signer";

interface SignedData {
  publicKey: string;
  data: string;
  signature: {
    field: string;
    scalar: string;
  };
}

const signResult: SignedData = req.body.signResult;
const minaClient = new Client({ network: "testnet" });
const isTrue = minaClient.verifyMessage(signResult);
```

**Comment by lvshaoping007** [comment]
I think we can discuss this in a chat group and it will be more efficient, what do you think?
discord and telegram. Which one do you prefer?

**Comment by Pfed-prog** [comment]
Absolutely, I have created small Mina related group recently https://t.me/+_IY-ANL4GV8yMzY0

**Comment by lvshaoping007** [comment]
Okay
