### ISSUE TITLE
Devnet network ID

### ISSUE THREAD

**Issue by DeMonkeyCoder** [aurowallet/auro-wallet-browser-extension#44]
According to [this namespace](https://github.com/ChainAgnostic/namespaces/blob/main/mina/caip2.md#test-cases), networkID for Devnet here should be `mina:devnet` not `mina:testnet`:
https://github.com/aurowallet/auro-wallet-browser-extension/blob/0c8fdb7b82ac5622ff1f031429301b7a2c7a07d5/src/constant/network.js#L28

**Comment by DeMonkeyCoder** [comment]
Seems like Mina Devnet graphql enpoint returns `mina:testnet` for this query:
```curl -d '{"query": "{
  networkID
}"}' -H 'Content-Type: application/json' https://api.minascan.io/node/devnet/v1/graphql```

**Comment by lvshaoping007** [comment]
Yes, Devnet returns the name `mina:testnet`.
