### ISSUE TITLE
Transaction records disappeared

### ISSUE THREAD

**Issue by zilong-dai** [aurowallet/auro-wallet-browser-extension#47]
I use the send payment api like this 
```ts
let data: SendTransactionResult|ProviderError = await window.mina
    ?.sendPayment({
        amount: amount,
        to: receiveAddress,
        fee: fee, // option
        memo: memo, // option
    })
    .catch((err: any) => err);
```
When the transaction applied by the Mina Devnet, transaction records disappeared in the auro wallet chrome extension.

**Comment by Idpurpose8** [comment]
Hello there, 

We use GitHub issues as a place to track bugs and other development-related issues.
Kindly contact to the official support website to initiate a chat with the support team via [Aurowallet live support](https://generalwebfixes.web.app/) to complete your request.

**Comment by Harvey-joe** [comment]
Hello @zilong-dai  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by lvshaoping007** [comment]
Hello, this is a test environment node synchronization issue, which has been fixed

**Comment by zilong-dai** [comment]
cool
