### ISSUE TITLE
toNonExponential returns wrong values

### ISSUE THREAD

**Issue by lukaw3d** [aurowallet/auro-wallet-browser-extension#9]
https://github.com/bitcat365/auro-wallet-browser-extension/blob/41174f7b59286bf80dfa8b3a897d4612bc0445fc/src/utils/utils.js#L20

```js
[toNonExponential('1e-2'), toNonExponential('1.0e-2'), toNonExponential('10e-2')]
> ["0.01", "0.10", "0.010"]
expected: ["0.01", "0.01", "0.1"]
```

See also: https://github.com/oasisprotocol/oasis-wallet-ext/issues/63

**Comment by lvshaoping007** [comment]
haha , i [fix this](https://github.com/aurowallet/auro-wallet-browser-extension/blob/master/src/utils/utils.js#L25) , thanks for your suggestion
